### ISSUE TITLE
EXTERNAL HARD DRIVE NOT WORKING

### ISSUE THREAD

**Issue by cpg77** [sameersharma2006/transmission-snap#2]
Hello Sameer Sharma

Firstly thank you so much for your work for allowing Transmission 4.0.6 to be used as a snap for Ubuntu.

Secondly I am a brand new, still wet behind the ears linux user, so any problems I have are serious to me.

I have just reinstalled Ubuntu to the latest and installed Transmission 4.0.6 through the App Center.

Unfortunately external hard drives are not working with Transmission 4.0.6 and the new installation of Ubuntu!!!!!!

I cannot change the download location or the incomplete torrent location to an external hard drive? Or set location or even verify any completed torrents that I move over to the external drive using Files Manager.

I have attached a picture of the problem

![Screenshot from 2024-09-13 19-31-27](https://github.com/user-attachments/assets/600013f9-c0de-4953-9846-fc4b19c125ff)

Please could you advise me on what to do, I would be super super grateful.

Thank You, Thank You, Thank You for your help

**Comment by cpg77** [comment]
Hi Sameer

I have resolved the problem at my end by uninstalling Transmission from the App Center and reinstalling it from the command line. Thank you anyways for all the work you have done for Open Source Software making the world a much better place.

Take care, be safe

**Comment by sameersharma2006** [comment]
Apologies for the delay in responding am traveling so bit busy.
It was an easy fix, transmission snap being a snap app has limited access to filesystem.
To resolve your issue, re-install transmission-snap and then in terminal ;
> snap connect transmission:removable-media :removable-media
