### ISSUE TITLE
version 4.0.6 snap cant open on ubuntu 24.04

### ISSUE THREAD

**Issue by binocry** [sameersharma2006/transmission-snap#3]

**Comment by sameersharma2006** [comment]
Hey there, i will need more details to help you.
Try using transmission via the terminal(type snap run transmission in the shell) & then copy & paste the terminal output here.

Also, the output of `snap version` will be helpful.

**Comment by binocry** [comment]
> Hey there, i will need more details to help you. Try using transmission via the terminal(type snap run transmission in the shell) & then copy & paste the terminal output here.
> 
> Also, the output of `snap version` will be helpful.

hi, sorry for late late reply. so i reinstall ubuntu 24.04 again and now your app run just fine
idk why, probably corrupt installation or something? its just so weird with unexpected bug like this

love your app, you also maintain audacious snap right? thank you
